# Generated by Django 6.0.2 on 2026-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Paste the Google Maps Embed URL (the src attribute from the iframe)', max_length=1000, null=True),
        ),
    ]
