# Generated by Django 6.0.2 on 2026-02-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Event end time e.g. 16:00', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Event start time e.g. 10:00', null=True),
        ),
    ]
